name: "Update locales sources"

on:
  push:
    branches:
      - "main"

jobs:
  push-on-transifex:
    name: "Push locales sources"
    uses: "froozeify/GLPI_plugin-translation-workflows/.github/workflows/transifex-push-sources.yml@demo-switch-core"
    secrets:
      transifex-token: "${{ secrets.TRANSIFEX_TOKEN }}"
