name: "Publish release"

on:
  push:
    tags:
       - '*'

jobs:
  publish-release:
    permissions:
      contents: "write"
    name: "Publish release"
    uses: "froozeify/GLPI_plugin-release-workflows/.github/workflows/publish-release.yml@switch-to-core-tools"
